// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/google/wire"
	"go_chat_v1_test/internal/chat"
	"go_chat_v1_test/internal/controllers"
	"go_chat_v1_test/internal/repository"
	"go_chat_v1_test/internal/services/impl"
)

// Injectors from wire.go:

// InitializeContainer 注入点
func InitializeContainer(configPath string) (*Container, func(), error) {
	config := ProvideConfig(configPath)
	appConfig := &config.App
	databaseConfig := &config.Database
	logConfig := &config.Log
	manager, cleanup, err := ProvideLog(logConfig)
	if err != nil {
		return nil, nil, err
	}
	mainDB, cleanup2, err := ProvideDB(appConfig, databaseConfig, logConfig, manager)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	repositoryRepository := ProvideUserRepository(mainDB)
	userRepository := repository.NewUserRepositoryImpl(repositoryRepository)
	kafkaConfig := &config.KafkaInfo
	mainKafkaProducer, cleanup3, err := ProvideKafkaProducer(kafkaConfig, manager)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mainKafkaConsumer, cleanup4, err := ProvideKafkaConsumer(kafkaConfig, manager)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	kafkaServices := impl.NewKafkaServiceImpl(mainKafkaProducer, mainKafkaConsumer)
	userServices := impl.NewUserServiceImpl(userRepository, kafkaServices)
	redisConfig := &config.Redis
	mainRedis, cleanup5, err := ProvideRedisService(redisConfig, manager)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	redisServices := impl.NewRedisServiceImpl(mainRedis, manager)
	userController := controllers.NewUserController(userServices, redisServices, manager)
	jwtConfig := config.JwtInfo
	authServices := impl.NewAuthServiceImpl(userRepository, redisServices, jwtConfig)
	commonServices := impl.NewCommonServiceImpl(redisServices)
	authController := controllers.NewAuthController(authServices, commonServices)
	healthController := controllers.NewHealthController()
	commonController := controllers.NewCommonController(commonServices)
	webSocketConfig := &config.WebSocketInfo
	roomFactory := chat.NewDefaultRoomFactory(manager, webSocketConfig)
	clientFactory := chat.NewDefaultClientFactory(manager, webSocketConfig)
	shardedHub, cleanup6, err := ProvideShardedHub(webSocketConfig, roomFactory, clientFactory, manager)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	webSocketHandler := chat.NewWebSocketHandler(shardedHub, clientFactory, roomFactory, redisServices, manager)
	webSocketController := controllers.NewWebSocketController(webSocketHandler)
	container := &Container{
		Config:              config,
		DB:                  mainDB,
		logger:              manager,
		UserRepo:            userRepository,
		UserService:         userServices,
		UserController:      userController,
		AuthController:      authController,
		HealthController:    healthController,
		CommonController:    commonController,
		WebSocketController: webSocketController,
		RedisService:        redisServices,
		AuthService:         authServices,
		KafkaService:        kafkaServices,
		CommonService:       commonServices,
	}
	return container, func() {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var ControllerSet = wire.NewSet(controllers.NewUserController, controllers.NewAuthController, controllers.NewHealthController, controllers.NewCommonController, controllers.NewWebSocketController)

var ChatSet = wire.NewSet(chat.NewDefaultClientFactory, chat.NewDefaultRoomFactory, chat.NewWebSocketHandler)
